# This is a basic workflow to help you get started with Actions
name: Win32Sample GitHub Release
on:
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
