name: GitHub Packaged Zip Release
on:
  push:
    tags:
      - 'v*'
      
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r win-x64 --non-self-contained
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'LLAS_Decryptor_${{  github.ref_name }}.zip'
        path: D:\a\LLASDecryptor\LLASDecryptor\LLASDecryptor.Interface\bin\Release\net6.0-windows\win-x64\publish\
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'LLAS_Decryptor_${{  github.ref_name }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
